import streamlit as st
import streamlit.components.v1 as components

st.title('Зорилт 1. Ядуурлыг устгах')

st.markdown('Ядуурлын бүх хэлбэрийг эцэс болгох')

st.write('Одоогоор мэдээлэл байхгүй байна.')

st.divider()

st.markdown("<p style='text-align: center; color: black;'>All plots generated by Our World In Data are under CC-BY License of Fair Use.</p>", unsafe_allow_html=True)
st.markdown("<p style='text-align: center; color: black;'>2024 © Green Dot Climate</p>", unsafe_allow_html=True)