import streamlit as st
import streamlit.components.v1 as components

st.title('Зорилт 14. Далай тэнгисийн нөөцийг хамгаалах')

st.markdown('Тогтвортой хөгжлийн зорилгоор далай, тэнгис, далайн нөөц баялгийг хамгаалах, тогтвортой ашиглах')
st.divider()
st.write('Одоогоор мэдээлэл байхгүй байна.')


if st.button("Цэс рүү буцах"):
    st.switch_page("00_📌_Эхлэл.py")

st.divider()


st.write('All plots generated by Our World In Data are under CC-BY License of Fair Use.')
st.write('2024 © Green Dot Climate')